.PHONY: clean All

All:
	@echo "----------Building project:[ project_0 - Debug ]----------"
	@cd "project_0" && "$(MAKE)" -f  "project_0.mk"
clean:
	@echo "----------Cleaning project:[ project_0 - Debug ]----------"
	@cd "project_0" && "$(MAKE)" -f  "project_0.mk" clean
